(print "Mary had a little lamb.")
(print (.format "Its fleece was white as {0}."  "snow"))
(print "And everywhere that Mary went.")
(print (* "."  10  ))

(setv end1  "C")
(setv end2  "h")
(setv end3  "e")
(setv end4  "e")
(setv end5  "s")
(setv end6  "e")
(setv end7  "B")
(setv end8  "u")
(setv end9  "r")
(setv end10  "g")
(setv end11  "e")
(setv end12  "r")

(print end1  end2  end3  end4  end5  end6)
(print end7  end8  end9  end10  end11  end12)
